apiVersion: v1
data:
    password: ENC[AES256_GCM,data:s1Vrxf/+Hfg6KT36,iv:GfDWh/XbxTnNGPhdXqABVNt0POinsV4h1w0RsnJPREU=,tag:0abPHH87Gq/B7suOY95qlw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: redis-auth
    namespace: redis
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-09-09T17:02:00Z"
    mac: ENC[AES256_GCM,data:e4XwI9k5zIe52YMGV6Bs1Xp/ZuboAuF/MLPcWlZaEBFQqbeRcyjM6GRmyl5R2LP7296xSxIC+/SLh3pZPYlJP4lSyWArVMsliGmp3e8kX6u1XpqvzGirsApRidN/jxEMU8awzMfTQ7eaXuUd2CpZoJQFM3PsqSK6w0FNZR9jmqc=,iv:lj+q3dHbh0hmU3BLelqk+FJMIeSq4aAnZRgYzuDezU0=,tag:0RLuRVsdjnwYuJ3cjeJ9Qg==,type:str]
    pgp:
        - created_at: "2021-09-09T17:01:59Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMAy9qdXn/YAJRAQv5ATJZIGMbVX+qhVXGiYYzwxmwUiircUu1DSilKoSYXAKi
            7BUEN+5oRbAS4F/BfNyW8vIXaqMLXm6puK9S1xd+hRuNSQaKqZ+MIPvSK0Vkrv4W
            da5C7cOT+VBNVJzuXXrjiU4SHrMWaWboaj8zvX1q4AxTtrg5XLisb2+xyCBdMBU0
            CZGyJLhdCwJQn7JdLmSFzIfdPkUijcHuFhF0Rb8Ms0dk005SPEyBLSnx+vxvggRy
            U/I5e0OTl0AzcfMGi0bpXqRptbMv6QaKDEDNQ6awRk9vDeLd/t7rtTenRWU5ByP/
            IWlsUuZH3TCC+V3uQnJ5LIoKw/e1k9UCQy/xw+q9p0PWMb3H378s7RX3FNyHylXZ
            qqKyX0BQjvJmRq7maH6/EU9V0VnsS3NVdhAitkLCGpf0Raw+Z+71dRoO1eXojnTs
            pZ3IONPS1itN6BDUBH5kaChlTTSItPCde/EcphXAbjh4rsSr0zuDRJ6JmBJgJ4Zi
            ZPek25MwxCF4aTiHdH/41GgBCQIVj2aZxpE8h1MKlES9zSenAi0oRpd2SsJ2J85F
            du0DiH7UYc7NfF8rAu4ZfaRp49B3AgdirB+kxH2BlJ+g38aMFxHrFORKXJoJVuDR
            IeMKXAaXUQiWAk9zxNd/RVaQ00AS9KKv6A==
            =ERHx
            -----END PGP MESSAGE-----
          fp: E636FFB311FF38F7BD895166FE6767DFE0FA02E2
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
