apiVersion: v1
data:
    password: ENC[AES256_GCM,data:FK/MAVSD6IeBY1HtTB6E7Q==,iv:QGHWWvIqOFkQYA54Sc41vLvyZHaeXYJQM0o9u+NcvQo=,tag:hSnerovuRt2aKaTOP2o2Mg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: redis-auth
    namespace: redis
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-09-09T17:19:12Z"
    mac: ENC[AES256_GCM,data:wk1GpxA3tQ5zP2yjjVjNLKjVqku7sFqgnmD9V6/iB1/GdcJrkD2WxCUpMAy75fpDVm451NISkRbnBTlp+4MA/NRs9cDYQtyXC/HkKxChF+mgoh4SoATwxmmk3agVqK9EqqyYAxt+1YfrOHnZX+foWohnEpXveZFPDN1P/OunrYI=,iv:tr/XWCZKNQbyh2Vr3AdJsx9BNdDK1lQeMYxj0/MGBi8=,tag:69OIEooDqrzeDoxuj4+lMA==,type:str]
    pgp:
        - created_at: "2021-09-09T17:19:12Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMAy9qdXn/YAJRAQv+N469emiAtGH/DNi7FhFtbYhq4b5bJaXjhbsJPbC6N2Ib
            S1Ya97wNwmw2xGTeLr0/oCulicPQpzOjUGThn8vcMZ0qYSXrcHGI0DTtTrUj1O6W
            YMiIBInpWkHbVVPGfVMIKUIpv+iaKDunJpE27RvlnGzZTyGRcEftX2Cw+KtSENzN
            TFyAMb/Q6cwLGjkrmidugocK5oOrpvlnmrFZcIYjOtV8nbohxCny5EA5yI8B0pUc
            CcPK6LTNIUpBehYilSp6NnSc6J5S+haYo6iIMokMkAzZCHcMNcrOCKSY4/+PEsEB
            xxKWx6b5CdcXIY849FuMqi6dRHv4Gv9SEPJvc0s3CYumfWksoEdl3Ekhd+jEcWoZ
            hYhr934NCYGpChPBzft1q8DqrIiToTP7PBoDhZZXlkMiIRfbPbSis3WcEkeoRNt1
            ixp/QHoFFmxTrzaJmHBBgco+F+DEFMvtjZpL9c0Io/Q2qH8wnmfzREKFjS72RJDy
            erMkaMbDZdIG9Wyhpx2N1GgBCQIVjHOsoSwOvhEKlrOvpEiyN08Aev+wXjayqtoE
            K8sPNl7qMcrPH32cOFw+NSDaArKF/hOLuHLqsmNLEIVq6lNdeMuOs2RljdeoX+2+
            jP+KvUyPnilV16JMs9Ea0bh/ijCPwbd8Qg==
            =lI2D
            -----END PGP MESSAGE-----
          fp: E636FFB311FF38F7BD895166FE6767DFE0FA02E2
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
